services:
  learning-platform-postgres:
    image: postgres:18
    container_name: learning-platform-postgres
    restart: on-failure
    env_file:
      - ../.env
    volumes:
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data-learning-platform:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  db-data-learning-platform: