services:
  learning-platform-redis:
    image: redis:latest
    container_name: learning-platform-redis
    restart: on-failure
    env_file:
      - ../.env
    ports:
      - "6379:6379"
    volumes:
      - redis-data-learning-platform:/root/redis

volumes:
  redis-data-learning-platform: