services:
  learning-platform-media:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
    container_name: learning-platform-media
    restart: on-failure
    depends_on:
      - learning-platform-minio
    ports:
      - "50057:50057"
    volumes:
      - ..:/app
