version: '3'

vars:
  PROTO_ROOT: protos/proto
  OUT_GO: protos/gen/go

tasks:
  gen:
    desc: "Generate proto for one service or all"
    cmds:
      - |
        if [ "{{.SERVICE}}" = "all" ] || [ -z "{{.SERVICE}}" ]; then
          protoc -I {{.PROTO_ROOT}} \
            {{.PROTO_ROOT}}/**/*.proto \
            --go_out={{.OUT_GO}} --go_opt=paths=source_relative \
            --go-grpc_out={{.OUT_GO}} --go-grpc_opt=paths=source_relative
        else
          protoc -I {{.PROTO_ROOT}} \
            {{.PROTO_ROOT}}/{{.SERVICE}}/*.proto \
            --go_out={{.OUT_GO}} --go_opt=paths=source_relative \
            --go-grpc_out={{.OUT_GO}} --go-grpc_opt=paths=source_relative
        fi
