export enum LeftMenuTabs {
    MAIN = "MAIN",
    SCHEDULE = "SCHEDULE",
    TUTORS = "TUTORS",
    SERVICES = "SERVICES",
    STUDY = "STUDY",
    COURSES = "COURSER",
    PRACTICES = "PRACTICES",
    MATERIALS = "MATERIALS",
    SERVICES_ITEMS = "SERVICES_ITEMS",
    SERVICES_ORDERS = "SERVICES_ORDERS",
}